import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/header'

const inter = Inter({
	weight: ['300', '400', '500', '600'],
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Word Wise Page',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} bg-background text-foreground antialiased`}
			>
				<div className='p-4'>
					<Header />
					<main>{children}</main>
				</div>
			</body>
		</html>
	)
}
